version: 2.1

jobs:
  build_and_deploy:
    machine:
        image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:
          name: Login to dockerhub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push udagram-api-feed to Dockerhub
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed tinhdh/udagram-api-feed:v1.0.0
            docker push tinhdh/udagram-api-feed:v1.0.0
      - run:
          name: Deploy udagram-api-user to Dockerhub
          command: |
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user tinhdh/udagram-api-user:v1.0.0
            docker push tinhdh/udagram-api-user:v1.0.0
      - run:
          name: Deploy udagram-frontend to Dockerhub
          command: |
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend tinhdh/udagram-frontend:v1.0.0
            docker push tinhdh/udagram-frontend:v1.0.0
      - run:
          name: Deploy udagram-reverseproxy to Dockerhub
          command: |
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy tinhdh/udagram-reverseproxy:v1.0.0
            docker push tinhdh/udagram-reverseproxy:v1.0.0

# Define workflows
workflows:
  default:
    jobs:
      - build_and_deploy
